
include $(TOPDIR)/rules.mk

LUCI_TITLE:=Modify Macaddress for luci
LUCI_DEPENDS:=
LUCI_PKGARCH:=all
PKG_VERSION:=5.99
PKG_RELEASE:=1

include $(TOPDIR)/feeds/luci/luci.mk
# call BuildPackage - OpenWrt buildroot signature
