#
# Copyright (C) 2008-2014 The LuCI Team <luci@lists.subsignal.org>
#
# This is free software, licensed under the Apache License, Version 2.0 .
#
#因为这个主题修改了luci的系统文件所以在安装的时候会提示index.lua和sysauth.htm已经衩其它包提供，安装前请先重命名这两个文件即可安装成功

include $(TOPDIR)/rules.mk

LUCI_TITLE:=Win10 Theme
LUCI_DEPENDS:=

include $(TOPDIR)/feeds/luci/luci.mk



# call BuildPackage - OpenWrt buildroot signature
